version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: '08:00'
    timezone: US/Pacific
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: '08:00'
    timezone: US/Pacific
  open-pull-requests-limit: 10
