version: '2.2'

services:

    api:
        cpus: 2
        mem_limit: 4G
        mem_reservation: 290m
        build: .
        environment:
            - RELOAD=--reload
            - PORT=5001
            - NUM_WORKERS=4
            - MPCONTRIBS_MONGO_HOST=$MPCONTRIBS_MONGO_HOST
            - DB_VERSION=2021_prerelease
        volumes:
            - .:/app
        ports:
            - "5001:5001"
