"""Define auxiliary schemas used by some LLMs."""
from __future__ import annotations

from typing import Any

from emmet.core.summary import SummaryDoc
from pydantic import BaseModel, Field, model_validator
from typing_extensions import Self

from mp_api.client.core.utils import validate_ids


class MaterialMetadata(BaseModel):
    """Define metadata associated to a material.

    These fields are a subset of the `emmet.core.summary.SummaryDoc`
    model fields, with a few extra fields to include
    robocrystallographer autogenerated descriptions and similarity scores.
    """

    nsites: int | None = Field(
        None,
        description="The number of sites in the structure as found on the Materials Project.",
    )

    nelements: int | None = Field(
        None, description="The number of unique elements in this structure."
    )
    formula_pretty: str | None = Field(
        None, description="The chemical formula of this material."
    )
    formula_anonymous: str | None = Field(
        None,
        description="The chemical formula of this material's prototype, i.e., without sp.",
    )
    chemsys: str | None = Field(
        None,
        description="A dash-delimited string separating the unique elements in this material.",
    )
    volume: float | None = Field(
        None,
        description="The volume of the structure associated with this material in cubic Angstrom (Å³).",
    )
    density: float | None = Field(
        None,
        description="The volume of the structure associated with this material in grams per cubic centimeter (g/cm³).",
    )
    density_atomic: float | None = Field(
        None,
        description="The volume per atom of the structure associated with this material in Å³/atom.",
    )

    space_group_number: int | None = Field(
        None,
        description="The international space group number of this material (Reference: https://en.wikipedia.org/wiki/Space_group#Table_of_space_groups_in_3_dimensions).",
    )

    space_group_symbol: str | None = Field(
        None,
        description="The international space group symbol of this material (Reference: https://en.wikipedia.org/wiki/Space_group#Table_of_space_groups_in_3_dimensions).",
    )

    crystal_system: str | None = Field(
        None,
        description="The crystal system of this material (Reference: https://en.wikipedia.org/wiki/Crystal_system)",
    )

    point_group: str | None = Field(None, description="The point group of the lattice.")

    material_id: str | None = Field(
        None,
        description="The Materials Project ID of this material, generally of the form `mp-1`, `mp-2`, etc.",
    )

    deprecated: bool = Field(
        True,
        description=(
            "If True, the Materials Project considers this material to be deprecated / untrustworthy. "
            "If False, the data contained herein should be considered robust."
        ),
    )

    formation_energy_per_atom: float | None = Field(
        None,
        description="The DFT-computed enthalpy of formation at zero kelvin (0K) with corrections, in eV/atom.",
    )

    energy_above_hull: float | None = Field(
        None,
        description=(
            "The energy above the thermodynamic hull for this material, in eV/atom. "
            "This quantity is non-negative. Zero indicates a stable material. "
            "Small values indicate slightly unstable materials, which may stabilize at "
            "higher temperatures. Large values indicate highly unstable materials."
        ),
    )

    is_stable: bool | None = Field(
        None,
        description="Whether this material lies on the hull, i.e., its `energy_above_hull` is almost zero.",
    )

    equilibrium_reaction_energy_per_atom: float | None = Field(
        None,
        description="The reaction energy of a stable entry from the neighboring equilibrium stable materials in eV."
        " Also known as the inverse distance to hull.",
    )

    band_gap: float | None = Field(
        None,
        description="The electronic band gap energy in eV.",
    )

    cbm: float | None = Field(
        None,
        description="The Conduction Band Minimum (CBM) in eV.",
    )

    vbm: float | None = Field(
        None,
        description="The Valence Band Maximum (VBM) in eV.",
    )

    efermi: float | None = Field(
        None,
        description="The Fermi energy (or Fermi level) in eV.",
    )

    is_gap_direct: bool | None = Field(
        None,
        description="Whether the band gap is direct.",
    )

    is_metal: bool | None = Field(
        None,
        description="Whether the material is a metal (`band_gap` = 0).",
    )

    is_magnetic: bool | None = Field(
        None,
        description="Whether the material is magnetic.",
    )

    ordering: str | None = Field(
        None,
        description=(
            "Type of collinear magnetic ordering: "
            "`NM` indicates non-magnetic, "
            "`FM` indicates ferromagnetic, "
            "`FiM` indicates ferrimagnetic, "
            "and `AFM` indicates antiferromagnetic."
        ),
    )

    total_magnetization: float | None = Field(
        None,
        description="Total magnetization in Bohr magneton, μB.",
    )

    total_magnetization_normalized_vol: float | None = Field(
        None,
        description="Total magnetization normalized by volume in μB/Å³.",
    )

    total_magnetization_normalized_formula_units: float | None = Field(
        None,
        description="Total magnetization normalized by formula unit in μB/(formula unit).",
    )

    num_magnetic_sites: int | None = Field(
        None,
        description="The number of magnetic sites.",
    )

    num_unique_magnetic_sites: int | None = Field(
        None,
        description="The number of unique magnetic sites.",
    )

    bulk_modulus_voigt: float | None = Field(
        None, description="Voigt average of the bulk modulus in gigapascal (GPa)."
    )

    bulk_modulus_reuss: float | None = Field(
        None, description="Reuss average of the bulk modulus in GPa."
    )

    bulk_modulus_vrh: float | None = Field(
        None, description="Voigt-Reuss-Hill average of the bulk modulus in GPa."
    )

    shear_modulus_voigt: float | None = Field(
        None, description="Voigt average of the shear modulus in GPa."
    )

    shear_modulus_reuss: float | None = Field(
        None, description="Reuss average of the shear modulus in GPa."
    )

    shear_modulus_vrh: float | None = Field(
        None, description="Voigt-Reuss-Hill average of the shear modulus in GPa."
    )

    universal_anisotropy: float | None = Field(
        None, description="Elastic anisotropy, dimensionless."
    )

    homogeneous_poisson: float | None = Field(
        None, description="Poisson ratio, dimensionless."
    )

    e_total: float | None = Field(
        None,
        description="Total dielectric constant, dimensionless.",
    )

    e_ionic: float | None = Field(
        None,
        description="Ionic contribution to dielectric constant, dimensionless.",
    )

    e_electronic: float | None = Field(
        None,
        description="Electronic contribution to dielectric constant, dimensionless.",
    )

    n: float | None = Field(
        None,
        description="The optical refractive index, dimensionless.",
    )

    theoretical: bool = Field(
        True,
        description=(
            "Whether the material has not been matched to a structure "
            "in an experimental database. If this is `True`, then both "
            "`linked_icsd_ids` and `linked_pf_ids` should be `None`."
        ),
    )

    linked_icsd_ids: str | None = Field(
        None,
        description=(
            "A comma-delimited list of Inorganic Crystal Structure Database "
            "(ICSD) identifiers of materials which have been matched to this "
            "material. Example: 'icsd-1, icsd-2, icsd-10'"
        ),
    )

    linked_pf_ids: str | None = Field(
        None,
        description=(
            "A comma-delimited list of Pauling File (pf) "
            "identifiers of materials which have been matched to this "
            "material. Example: 'pf-1, pf-2, pf-10'"
        ),
    )

    structurally_similar_materials: str | None = Field(
        None,
        description=(
            "A comma-delimited list of structurally similar materials "
            "in the Materials Project, with additional information about their "
            "chemistry and similarity ranking. Example: "
            r"'mp-104: LiS (98.1% similar); mp-50505: NaP (94.3% similar)'"
        ),
    )

    cell_vectors: list[list[float]] | None = Field(
        None,
        description=(
            "The 3x3 array of (lattice) cell vectors, all values in Å."
            "The first row is the a vector, the second the b vector, "
            "and the third the c vector."
        ),
    )

    atoms: list[str] | None = Field(
        None,
        description=(
            "A list of atom symbols on each site. Should have length `nsites`."
        ),
    )

    cartesian_coordinates: list[list[float]] | None = Field(
        None,
        description=(
            "A `nsites` x 3 array of floats, all values in Å, "
            "representing the Cartesian coordinates of the atoms."
            "The order is the same as in `atoms`."
        ),
    )
    magnetic_moments: list[float] | None = Field(
        None,
        description=(
            "A `nsites` array of floats, all values in μB, representing "
            "the on-site magnetic moments found by integrating the "
            "electronic spin density in a sphere surrounding each site "
            "in the structure."
        ),
    )

    @staticmethod
    def _summary_fields() -> list[str]:
        """Get a list of the fields needed in a SummaryDoc to populate this document."""
        return [
            *(set(MaterialMetadata.model_fields) & set(SummaryDoc.model_fields)),
            # The following fields get renamed and flattened in `MaterialMetadata`
            "structure",
            "bulk_modulus",
            "shear_modulus",
            "database_IDs",
            "symmetry",
        ]

    @classmethod
    def from_summary_data(cls, summary_data: dict[str, Any], **kwargs) -> Self:
        """Create a MaterialMetadata document from materials summary data.

        Args:
            summary_data : dict of str to Any
                The dict representation of an `emmet.core.summary.SummaryDoc`
                document (i.e., its `model_dump_json`)
            **kwargs : to pass to `MaterialMetadata`
        """
        metadata = {
            **kwargs,
            **{
                k: summary_data[k]
                for k in MaterialMetadata.model_fields
                if summary_data.get(k) is not None
            },
        }
        for k in {"bulk", "shear"}:
            if summary_data.get(f"{k}_modulus"):
                metadata.update(
                    {
                        f"{k}_modulus_{v}": summary_data[f"{k}_modulus"].get(v)
                        for v in ("voigt", "reuss", "hill")
                    }
                )

        # Augment with experimental database id information
        if summary_data.get("database_IDs"):
            metadata.update(
                {
                    f"linked_{database}_ids": ", ".join(matched_ids)
                    for database, matched_ids in summary_data["database_IDs"].items()
                }
            )

        if (symm_meta := summary_data.get("symmetry")) is not None:
            metadata.update(
                {
                    k: symm_meta.get(v)
                    for k, v in {
                        "space_group_number": "number",
                        "space_group_symbol": "symbol",
                        "crystal_system": "crystal_system",
                        "point_group": "point_group",
                    }.items()
                }
            )

        # flatten structure data
        if struct_dict := summary_data.get("structure"):
            magnetic_moments = [
                site["properties"].get("magmom") for site in struct_dict["sites"]
            ]
            metadata.update(
                cell_vectors=struct_dict["lattice"]["matrix"],
                atoms=[site["species"][0]["element"] for site in struct_dict["sites"]],
                cartesian_coordinates=[site["xyz"] for site in struct_dict["sites"]],
                magnetic_moments=(
                    None
                    if any(magmom is None for magmom in magnetic_moments)
                    else magnetic_moments
                ),
            )

        return cls(**metadata)


class FetchResult(BaseModel):
    """Schematize result of the `fetch` MCP tool.

    This schema is designed for compatibility with OpenAI's spec:
    https://platform.openai.com/docs/mcp#fetch-tool

    However it should be compatible with other LLMs as well.
    """

    id: str = Field(
        description="The Materials Project ID of this entry, of the form `mp-13`."
    )
    title: str | None = Field(None, description="Typically the Materials Project ID.")
    text: str | None = Field(
        None,
        description="The robocrystallographer autogenerated description of this material.",
    )
    url: str | None = Field(None, description="A link to the Materials Project website")
    metadata: MaterialMetadata | None = Field(
        None,
        description="Auxiliary materials data aggregated from the summary and similarity collections in the Materials Project.",
    )

    @model_validator(mode="before")
    def set_url(cls, config: Any) -> Any:
        """Set default Materials Project URL and title."""
        formatted_mpid = validate_ids([config.get("id")])[0]
        if not config.get("title"):
            config["title"] = formatted_mpid

        if not config.get("url"):
            config["url"] = (
                "https://next-gen.materialsproject.org/materials/" f"{formatted_mpid}"
            )
        return config


class SearchOutput(BaseModel):
    """Schematize data for the MCP `search` tool.

    This schema is designed for compatibility with OpenAI's spec:
    https://platform.openai.com/docs/mcp#search-tool

    But will also be compatible with most other LLMs.
    """

    results: list[FetchResult] = Field([], description="A list of results")
